server:
  port: 9090

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowCredentials: true
#            allowedOrigins: "http://192.168.0.108:8080"
            allowedHeaders: "*"
            allowedMethods: "*"
            exposedHeaders: "Authorization"
      default-filters:
        - TokenRelay
      routes:
        - id: product-service
          uri: http://192.168.0.108:9091
          predicates:
            - Path=/product/**
          metadata:
            allowCredentials: true
#            allowedOrigins: 'http://192.168.0.108:8080'
            allowedHeaders: '*'
            allowedMethods: '*'
            exposedHeaders: 'Authorization'
            maxAge: 30

  security:
    oauth2:
      #      resourceserver:
      #        jwt:
      #          jwk-set-uri: ${kc.server-url}/realms/${kc.realm}/protocol/openid-connect/certs
      resourceserver:
        opaquetoken:
          introspection-uri: ${kc.server-url}/realms/${kc.realm}/protocol/openid-connect/token/introspect
          client-id: api-gateway
          client-secret: 4r7LcqUunWxfKukwdVPmkobyk7wtAj4Z
kc:
  server-url: https://auth.uzgps.uz:8443/auth
  realm: spring-realm